### ISSUE TITLE
CLI Compatibility

### ISSUE THREAD

**Issue by vvondra** [vvondra/bitwarden-serverless#23]
Currently the Bitwarden CLI doesn't work, a new endpoint managing user keys is needed, perhaps more:

```
$ bw login me@gmail.com
? Master password: **123***123***123****
? Two-step login code: 123123
{ FetchError: invalid json response body at https://testenv.com/api/accounts/keys reason: Unexpected token N in JSON at position 0
    at /Users/me/.nvm/versions/node/v9.4.0/lib/node_modules/@bitwarden/cli/build/bw.js:32497:32
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  message: 'invalid json response body at https://testenv.com/api/accounts/keys reason: Unexpected token N in JSON at position 0',
  type: 'invalid-json' }
You are logged in!
```

I suspect the error is caused by a simple "Not Found" message response

Support for CLI will be also needed to fix #21

**Comment by vvondra** [comment]
closed by 42e99009b490c62df32147118a4e05ef306c5deb
