### ISSUE TITLE
2FA - having issues getting activated.

### ISSUE THREAD

**Issue by amx-jshriner** [vvondra/bitwarden-serverless#71]
First, thanks for the great work done on this project!

I am having some issues however, with 2FA. The initial error, which I've since possibly worked around, was the issue "Email not supplied" when passing the email into the `two_factor_auth.sh`, as seen in the image below...

![image](https://user-images.githubusercontent.com/58048071/70630701-fe91dc00-1bf9-11ea-96e9-050dbbbbd19a.png)

Notice, I added an `echo` in the script to see what values it was passing.

I then went and edited the script by adding a space after `-d` so it would pass the correct value along for email. After that, the URL seemed to just be a Base64 encoded string...

![image](https://user-images.githubusercontent.com/58048071/70631134-b3c49400-1bfa-11ea-96d3-2ed704d8b692.png)

I then decoded the string into an image using https://codebeautify.org/base64-to-image-converter.

At this point, 2FA is active on my account and Authy can generate tokens. However, at this point, I cannot login the account in either the Chrome Add-on or the CLI .

```
bw login jshriner@arbormetrix.com --method 0 --code 340021
? Master password: [hidden]
(node:2103) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'message' of null
    at Function.error (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:21317:33)
    at commands_login_command_LoginCommand.<anonymous> (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:23231:33)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:23101:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2103) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2103) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have since been locked out of my Bitwarden and unable to find a resolution. Any advice is greatly appreciated!

**Comment by amx-jshriner** [comment]
Just commenting to say I want able to get this working by going into the AWS Console, into the API Gateway related to the bitwarden-serverless customdomain and explicitly set the base path to prod. Thanks again for the great project!
